/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
  }
}
